# Generated by Django 3.2 on 2021-05-03 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(choices=[('Speaker', 'speaker'), ('Headphones', 'headphones'), ('Laptop', 'laptop'), ('Fridge', 'fridge')], default='income', max_length=200),
        ),
    ]
