# Generated by Django 3.2 on 2021-05-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0005_product_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='account',
            field=models.IntegerField(choices=[('PRODUCT AMOUNT', 'PRODUCT AMOUNT'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], default='PRODUCT AMOUNT'),
        ),
    ]
