# Generated by Django 3.2 on 2021-05-03 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0006_alter_product_account'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='account',
            new_name='amount',
        ),
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
    ]
