# Generated by Django 3.2 on 2021-05-03 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0008_transactions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='amount',
        ),
        migrations.AlterField(
            model_name='product',
            name='item',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='amount',
            field=models.IntegerField(default=0),
        ),
    ]
