# Generated by Django 3.2 on 2021-05-05 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0009_auto_20210503_1901'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='amount',
        ),
    ]
