# Generated by Django 3.2 on 2021-05-05 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0010_remove_transactions_amount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.IntegerField(choices=[(1, 'Headphones'), (2, 'Fridge'), (3, 'Speaker'), (4, 'Laptop')])),
            ],
        ),
    ]
