# Generated by Django 3.2 on 2021-05-05 03:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0011_products'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Products',
        ),
    ]
