# Generated by Django 3.2 on 2021-05-06 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0013_transactions_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transactions',
            name='item',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
